import 'package:qualif_flutter/models/anime_model.dart';
import 'package:qualif_flutter/models/comment_model.dart';


class Data{
    static List<Anime> animeList = [
    Anime(
      title: "Bocchi The Rock", 
      description: "Hitori Gotou, 'Bocchi-chan,' is a girl who’s so introverted and shy around people that she’d always start her conversations with 'Ahh...'. During her middle school years, she started playing the guitar, wanting to join a band because she thought it could be an opportunity for even someone shy like her to also shine. But because she had no friends, she ended up practicing guitar for six hours every day all by herself. After becoming a skilled guitar player, she uploaded videos of herself playing the guitar to the internet under the name “Guitar Hero” and fantasized about performing at her school’s cultural festival concert. But not only could she not find any bandmates, before she knew it, she was in high school and still wasn’t able to make a single friend! She was really close to becoming a shut-in, but one day, Nijika Ijichi, the drummer in Kessoku Band, reached out to her. And because of that, her everyday life started to change little by little...", 
      image: "assets/cover/cover1.png", 
      rating: "8.83",
      genre: ["Music", "Comedy", "Slice of Life"],
      banner: "assets/banner/banner1.jpg",
      comments: [Comment(content: "aaa", commenter: "JE")],
    ),
    Anime(
      title: "Oshi no Ko", 
      description: "When a pregnant young starlet appears in Gorou Amemiya’s countryside medical clinic, the doctor takes it upon himself to safely (and secretly) deliver Ai Hoshino’s child so she can make a scandal-free return to the stage. But no good deed goes unpunished, and on the eve of her delivery, he finds himself slain at the hands of Ai’s deluded stalker — and subsequently reborn as Ai’s child, Aquamarine Hoshino! The glitz and glamor of showbiz hide the dark underbelly of the entertainment industry, threatening to dull the shine of his favorite star. Can he help his new mother rise to the top of the charts? And what will he do when unthinkable disaster strikes?", 
      image: "assets/cover/cover2.png", 
      rating: "8.81",
      genre: ["Drama", "Mystery", "Psychological"],
      banner: "assets/banner/banner2.jpg",
      comments: [],
    ),
    Anime(
      title: "K-ON!", 
      description: "Hirasawa Yui, a young, carefree girl entering high school, has her imagination instantly captured when she sees a poster advertising the ‘Light Music Club’. Being the carefree girl that she is, she quickly signs up. However, Yui has a problem, she is unable to play an instrument. When Yui goes to the clubroom to explain, she's greeted by the other members: Ritsu, Mio and Tsumugi. Although disheartened at Yui’s lack of musical know-how, they still try to convince her to stay to prevent the club’s disbandment. After playing Yui a short piece which re-ignites her imagination, they succeed in keeping their new member and guitarist. Along with the tasks of school and homework, Yui begins to learn the guitar with the help of the other band members, experiencing many mishaps along the way. However, with the school-festival drawing near and Yui getting stuck with her practice, will the Light Music Club be ready in time for their debut?", 
      image: "assets/cover/cover3.png", 
      rating: "8.81",
      genre: ["Music", "Comedy", "Slice of Life"],
      banner: "assets/banner/banner3.jpg",
      comments: [],
    ),
    Anime(
      title: "Jujutsu Kaisen 2nd Season", 
      description: "The past comes to light when second-year students Satoru Gojou and Suguru Getou are tasked with escorting young Riko Amanai to Master Tengen. But when a non-sorcerer user tries to kill them, their mission to protect the Star Plasma Vessel threatens to turn them into bitter enemies and cement their destinies—one as the world’s strongest sorcerer, and the other its most twisted curse user!", 
      image: "assets/cover/cover4.jpg", 
      rating: "8.81",
      genre: ["Action", "Drama", "Supernatural"],
      banner: "assets/banner/banner4.jpg",
      comments: [],
    ),
    Anime(
      title: "Zom 100: Zombie ni Naru Made ni Shitai 100 no Koto", 
      description: "Surviving a zombie apocalypse beats being a wage slave any day! After spending years slaving away for a soul-crushing company, Akira's life has lost its luster. He lives in a trash-filled apartment, his pay is abysmal, and he can't even muster up the nerve to confess his love to his beautiful co-worker. But when a zombie apocalypse ravages his town, it gives him the push he needs to live for himself. Now Akira's on a mission to complete all 100 items on his bucket list before he...well, kicks the bucket.", 
      image: "assets/cover/cover5.png", 
      rating: "8.26",
      genre: ["Action", "Comedy", "Horror"],
      banner: "assets/banner/banner5.jpg",
      comments: [],
    ),
    Anime(
      title: "SPY x FAMILY", 
      description: "Everyone has a part of themselves they cannot show to anyone else. At a time when all nations of the world were involved in a fierce war of information happening behind closed doors, Ostania and Westalis had been in a state of cold war against one another for decades. The Westalis Intelligence Services' Eastern-Focused Division (WISE) sends their most talented spy, 'Twilight,' on a top-secret mission to investigate the movements of Donovan Desmond, the chairman of Ostania's National Unity Party, who is threatening peace efforts between the two nations. This mission is known as 'Operation Strix.' It consists of 'putting together a family in one week in order to infiltrate social gatherings organized by the elite school that Desmond's son attends.' 'Twilight' takes on the identity of psychiatrist Loid Forger and starts looking for family members. But Anya, the daughter he adopts, turns out to have the ability to read people's minds, while his wife, Yor, is an assassin! With it being in each of their own interests to keep these facts hidden, they start living together while concealing their true identities from one another. World peace is now in the hands of this brand-new family as they embark on an adventure full of surprises.", 
      image: "assets/cover/cover6.jpg", 
      rating: "8.6",
      genre: ["Comedy", "Action", "Slice of Life"],
      banner: "assets/banner/banner6.jpg",
      comments: [],
    ),
    Anime(
      title: "A Silent Voice", 
      description: "After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. As Shouya continues to bully Shouko, the class turns its back on him. Shouko transfers and Shouya grows up as an outcast. Alone and depressed, the regretful Shouya finds Shouko to make amends.", 
      image: "assets/cover/cover7.jpg", 
      rating: "8.94",
      genre: ["Drama", "Romance", "Slice of Life"],
      banner: "assets/banner/banner7.jpg",
      comments: [],
    ),
    Anime(
      title: "Kaguya-sama: Love is War", 
      description: "Known for being both brilliant and powerful, Miyuki Shirogane and Kaguya Shinomiya lead the illustrious Shuchiin Academy as near equals. And everyone thinks they’d make a great couple. Pride and arrogance are in ample supply, so the only logical move is to trick the other into instigating a date! Who will come out on top in this psychological war where the first move is the only one that matters?", 
      image: "assets/cover/cover8.jpg", 
      rating: "8.41",
      genre: ["Romance", "Comedy", "Psychological"],
      banner: "assets/banner/banner8.jpg",
      comments: [],
    ),
    Anime(
      title: "My Dress-Up Darling", 
      description: "High schooler Wakana Gojou cares about one thing: making Hina dolls. With nobody to share his obsession, he has trouble finding friends—or even holding conversation. But after the school’s most popular girl, Marin Kitagawa, reveals a secret of her own, he discovers a new purpose for his sewing skills. Together, they’ll make her cosplay dreams come true!", 
      image: "assets/cover/cover9.jpg", 
      rating: "8.23",
      genre: ["Comedy", "Romance", "Slice of Life"],
      banner: "assets/banner/banner9.jpg",
      comments: [],
    ),
    Anime(
      title: "Assassination Classroom 2", 
      description: "The students return as school is back in session for the second semester. Following their exploits on the island during summer vacation, Class 3-E continues to sharpen their blades with their sights set on their teacher, the slippery Koro-sensei. They have more to worry about than just their teacher, however, as enemy assassins, both old and new, are out for the increased bounty on the octopus' head. Moreover, their rivals in Class A, as well as Kunugigaoka Junior High's fearsome principal, stand to block Class E from achieving academic excellence. With all of these obstacles opposing them, the group must continue to work together in order to overcome their foes and accomplish their goal of successfully assassinating their teacher.", 
      image: "assets/cover/cover10.jpg", 
      rating: "8.49",
      genre: ["Action", "Comedy", "Drama"],
      banner: "assets/banner/banner10.jpg",
      comments: [],
    ),
    Anime(
      title: "Your lie in April", 
      description: "Piano prodigy Arima Kousei dominated the competition and all child musicians knew his name. But after his mother, who was also his instructor, passed away, he had a mental breakdown while performing at a recital. This resulted in him no longer being able to hear the sound of his piano playing. Two years later, Kousei hasn’t touched the piano and views the world without any flair or color. He was content at living out his life with his good friends Tsubaki and Watari until, one day, a girl changed everything. Miyazono Kaori is a pretty, free spirited violinist whose playing style reflects her personality. Kaori helps Kousei return to the music world and show that it should be free and mold breaking unlike the structured and rigid style Kousei was used to.", 
      image: "assets/cover/cover11.png", 
      rating: "8.65",
      genre: ["Drama", "Music", "Romance"],
      banner: "assets/banner/banner11.jpg",
      comments: [],
    ),
    Anime(
      title: "Hibike! Euphonium", 
      description: "Spring in the first year of high school. Kumiko, a member of the brass band in junior high school, visits the high school brass band club with classmates Hazuki and Sapphire. There, she comes across Reina, her former classmate from junior high. Hazuki and Sapphire decide to join the club, but Kumiko can’t make up her mind. She recollects her experience with Reina at a competition in junior high school.", 
      image: "assets/cover/cover12.jpg", 
      rating: "8.00",
      genre: ["Drama", "Music", "Slice of Life"],
      banner: "assets/banner/banner12.jpg",
      comments: [],
    ),
    Anime(
      title: "Weathering With You", 
      description: "High school student Hodaka leaves his home on an isolated island and moves to Tokyo, but he immediately becomes broke. He lives his days in isolation, but finally finds a job as a writer for a shady occult magazine. After he starts his job, the weather has been rainy day after day. In a corner of the crowded and busy city, Hodaka meets a young woman named Hina. Due to certain circumstances, Hina and her younger brother live together, but have a cheerful and sturdy life. Hina also has a certain power: the power to stop the rain and clear the sky.", 
      image: "assets/cover/cover13.png", 
      rating: "8.29",
      genre: ["Drama", "Romance", "Slice of Life"],
      banner: "assets/banner/banner13.jpg",
      comments: [],
    ),
    Anime(
      title: "Mushoku Tensei: Jobless Reincarnation Season 2", 
      description: "The second season of Mushoku Tensei: Isekai Ittara Honki Dasu. Rudeus heads north with new friends and powers in search of adventure and those he once knew.", 
      image: "assets/cover/cover14.jpg", 
      rating: "8.58",
      genre: ["Adventure", "Drama", "Fantasy"],
      banner: "assets/banner/banner14.jpg",
      comments: [],
    ),
    Anime(
      title: "Suzume", 
      description: "The story follows Suzume, a 17-year-old girl from a quiet Kyushu town who meets a young man looking for a door. They find a door within ruins in the mountain, and Suzume opens it. Soon, more doors begin to open around Japan, bringing disasters from the other side. The film depicts Suzume's liberation and growth, as she closes the doors that are causing disaster.", 
      image: "assets/cover/cover15.jpg", 
      rating: "8.38",
      genre: ["Adventure", "Fantasy", "Mystery"],
      banner: "assets/banner/banner15.jpg",
      comments: [],
    ),
    Anime(
      title: "Yuru Camp", 
      description: "Rin likes to go camping by herself along the lakes that provide a scenic view of Mt. Fuji. Nadeshiko loves to take cycling trips by herself to places where she can see Mt. Fuji. After they meet, Rin and Nadeshiko take camping trips, eat cup ramen together, and enjoy the scenery.", 
      image: "assets/cover/cover16.jpg", 
      rating: "8.27",
      genre: ["Comedy", "Romance", "Slice of Life"],
      banner: "assets/banner/banner16.jpg",
      comments: [],
    ),
    Anime(
      title: "Lycoris Recoil", 
      description: "'LycoReco' is a café with a traditional Japanese twist located in downtown Tokyo. But the delicious coffee and sugary sweets are not the only orders this café takes! From delivering packages short distances, to pick-ups and drop-offs on the lonely streets at night, to zombies and giant monster extermination…?! Whatever your problem, we're here to help! We will solve any kind of 'trouble' you may have! Waiting for you are the ever-smiling poster-girl and the cool, serious newcomer. A petite girl who never wants to work and a young woman approaching thirty who wants to get married. And the manager is a nice guy who’s obsessed with Japan!", 
      image: "assets/cover/cover17.jpg", 
      rating: "8.19",
      genre: ["Action", "Comedy", "Slice of Life"],
      banner: "assets/banner/banner17.jpg",
      comments: [],
    ),
    Anime(
      title: "Anohana: The Flower We Saw That Day", 
      description: "Jinta Yadomi and his group of childhood friends have become estranged after a tragic accident split them apart. Now in their high school years, a sudden surprise forces each of them to confront their guilt over what happened that day and come to terms with the ghosts of their past.", 
      image: "assets/cover/cover18.jpg", 
      rating: "8.31",
      genre: ["Drama", "Romance", "Slice of Life"],
      banner: "assets/banner/banner18.jpg",
      comments: [],
    ),
    Anime(
      title: "My Teen Romantic Comedy SNAFU TOO!", 
      description: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku picks up immediately after the events of the first season, continuing the adventures of the Volunteer Service Club—the dispassionate Hachiman Hikigaya, the cheerful Yui Yuigahama, and the competitive Yukino Yukinoshita—as it dedicates itself to helping any student with issues that they may face. With the rift among his own group widening, Hachiman begins to realize that his knack for quickly getting to the root of other people's troubles is a double-edged sword: sometimes the best solution is not necessarily the most appropriate one.", 
      image: "assets/cover/cover19.png", 
      rating: "8.21",
      genre: ["Drama", "Romance", "Slice of Life"],
      banner: "assets/banner/banner19.jpg",
      comments: [],
    ),
    Anime(
      title: "5 Centimeters per Second", 
      description: "Tohno Takaki and Shinohara Akari, two very close friends and classmates, are torn apart when Akari's family is transferred to another region of Japan due to her family's job. Despite separation, they continue to keep in touch through mail. When Takaki finds out that his family is also moving, he decides to meet with Akari one last time. As years pass by, they continue down their own paths, their distance slowly growing wider and their contact with one another fades. Yet, they keep remembering one another and the times they have shared together, wondering if they will have the chance to meet once again.", 
      image: "assets/cover/cover20.jpg", 
      rating: "7.57",
      genre: ["Drama", "Romance", "Slice of Life"],
      banner: "assets/banner/banner20.jpg",
      comments: [],
    ),
  ];

  static List<Anime> myList = [];
  static List<Anime> favList = [];
  static List<Anime> romanceAnime = animeList.where((element) => element.genre.contains("Romance")).toList();
  static List<Anime> sliceOfLifeAnime = animeList.where((element) => element.genre.contains("Slice of Life")).toList();
  static List<Anime> actionAnime = animeList.where((element) => element.genre.contains("Action")).toList();


}